//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentChallenge.Data.Localizacion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevelopmentChallenge.Data.Localizacion.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area {0}.
        /// </summary>
        internal static string AREA {
            get {
                return ResourceManager.GetString("AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Circles.
        /// </summary>
        internal static string CIRCULO_PLURAL {
            get {
                return ResourceManager.GetString("CIRCULO_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Circle.
        /// </summary>
        internal static string CIRCULO_SINGULAR {
            get {
                return ResourceManager.GetString("CIRCULO_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Squares.
        /// </summary>
        internal static string CUADRADO_PLURAL {
            get {
                return ResourceManager.GetString("CUADRADO_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Square.
        /// </summary>
        internal static string CUADRADO_SINGULAR {
            get {
                return ResourceManager.GetString("CUADRADO_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} shapes.
        /// </summary>
        internal static string FORMA_PLURAL {
            get {
                return ResourceManager.GetString("FORMA_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} shape.
        /// </summary>
        internal static string FORMA_SINGULAR {
            get {
                return ResourceManager.GetString("FORMA_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes report.
        /// </summary>
        internal static string LISTA_CABECERA {
            get {
                return ResourceManager.GetString("LISTA_CABECERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty list of shapes!.
        /// </summary>
        internal static string LISTA_VACIA {
            get {
                return ResourceManager.GetString("LISTA_VACIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter {0}.
        /// </summary>
        internal static string PERIMETRO {
            get {
                return ResourceManager.GetString("PERIMETRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL.
        /// </summary>
        internal static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Triangles.
        /// </summary>
        internal static string TRIANGULO_PLURAL {
            get {
                return ResourceManager.GetString("TRIANGULO_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Triangle.
        /// </summary>
        internal static string TRIANGULO_SINGULAR {
            get {
                return ResourceManager.GetString("TRIANGULO_SINGULAR", resourceCulture);
            }
        }
    }
}
